// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_p9FRGfk1JfzuTqAgT9bQHEBJ-62-Iqs',
    appId: '1:890088669754:web:949597939c747321ff2b03',
    messagingSenderId: '890088669754',
    projectId: 'gp-firebase-ornek',
    authDomain: 'gp-firebase-ornek.firebaseapp.com',
    databaseURL: 'https://gp-firebase-ornek-default-rtdb.firebaseio.com',
    storageBucket: 'gp-firebase-ornek.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9DDxGfPvK1pbS1VSiIiKVo9O28qaIqWk',
    appId: '1:890088669754:android:52295acca971f529ff2b03',
    messagingSenderId: '890088669754',
    projectId: 'gp-firebase-ornek',
    databaseURL: 'https://gp-firebase-ornek-default-rtdb.firebaseio.com',
    storageBucket: 'gp-firebase-ornek.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqSeMIHuM_dcXkMxOWsu4vQ1tUVROp-Sk',
    appId: '1:890088669754:ios:589165034afbca1bff2b03',
    messagingSenderId: '890088669754',
    projectId: 'gp-firebase-ornek',
    databaseURL: 'https://gp-firebase-ornek-default-rtdb.firebaseio.com',
    storageBucket: 'gp-firebase-ornek.appspot.com',
    iosClientId: '890088669754-b9nf0pf27e6rsq5efnd8ilsc4dnelc2h.apps.googleusercontent.com',
    iosBundleId: 'com.example.tweets',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqSeMIHuM_dcXkMxOWsu4vQ1tUVROp-Sk',
    appId: '1:890088669754:ios:589165034afbca1bff2b03',
    messagingSenderId: '890088669754',
    projectId: 'gp-firebase-ornek',
    databaseURL: 'https://gp-firebase-ornek-default-rtdb.firebaseio.com',
    storageBucket: 'gp-firebase-ornek.appspot.com',
    iosClientId: '890088669754-b9nf0pf27e6rsq5efnd8ilsc4dnelc2h.apps.googleusercontent.com',
    iosBundleId: 'com.example.tweets',
  );
}
